- id: check-notebooks
  name: check notebooks
  description: check Jupyter Notebook contents
  entry: check_notebooks
  language: python
  stages: [pre-commit]
  types: [jupyter]

- id: check-notebook-open-atmos-structure
  name: check notebook has open-atmos structure
  entry: check_notebook_open_atmos_structure
  description: check notebook has open-atmos structure
  language: python
  stages: [pre-commit]
  types: [jupyter]

- id: check-notebook-output
  name: check notebook output
  description: check if notebooks are executed and without errors and warnings
  entry: check_notebook_output
  language: python
  stages: [pre-commit]
  types: [jupyter]

- id: check-notebook-using-jupyter-utils
  name: check notebook using open-atmos-jupyter-utils
  description: check if notebook use show_anim() and show_plot() methods from open-atmos-jupyter-utils
  entry: check_notebook_using_jupyter_utils
  language: python
  stages: [pre-commit]
  types: [jupyter]
