#!/usr/bin/env python3
"""
Checks notebook execution status for Jupyter notebooks"""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from .utils import open_and_test_notebooks, cell_error


def test_jetbrains_bug_py_66491(notebook, filename):
    """checks if all notebook have the execution_count key for each cell in JSON,
    which is required by GitHub renderer and may not be generated by some buggy PyCharm versions:
    https://youtrack.jetbrains.com/issue/PY-66491"""
    for idx, cell in enumerate(notebook.cells):
        if cell.cell_type == "code" and not hasattr(cell, "execution_count"):
            yield cell_error(
                filename,
                idx,
                code="NB000",
                message="Notebook cell missing execution_count attribute. "
                "(May be due to PyCharm bug, see: https://youtrack.jetbrains.com/issue/PY-66491 )",
            )


def main(argv: Sequence[str] | None = None) -> int:
    """Test all notebooks"""

    parser = argparse.ArgumentParser()
    parser.add_argument("filenames", nargs="*", help="Filenames to check.")
    args = parser.parse_args(argv)

    return open_and_test_notebooks(
        filenames=args.filenames,
        test_functions=[
            test_jetbrains_bug_py_66491,
        ],
    )


if __name__ == "__main__":
    raise SystemExit(main())
